// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestoFlow.Infrastructure.Data;

#nullable disable

namespace RestoFlow.Infrastructure.Migrations
{
    [DbContext(typeof(RestoFlowDbContext))]
    [Migration("20230626172302_include-isDeleted-flag")]
    partial class includeisDeletedflag
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RestoFlow.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RestoFlow.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Main Dishes"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Salads"
                        });
                });

            modelBuilder.Entity("RestoFlow.Infrastructure.Data.Models.OccupiedTable", b =>
                {
                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("TableId", "UserId", "OrderId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("OccupiedTables");
                });

            modelBuilder.Entity("RestoFlow.Infrastructure.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EditedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsServed")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("EditedById");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestoFlow.Infrastructure.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Fresh salmon fillet grilled to perfection and served with a side of steamed vegetables.",
                            Img = "grilled_salmon.jpg",
                            IsDeleted = false,
                            Name = "Grilled Salmon"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Tender breaded chicken breast topped with marinara sauce and melted mozzarella cheese, served with pasta.",
                            Img = "chicken_parmesan.jpg",
                            IsDeleted = false,
                            Name = "Chicken Parmesan"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Juicy beef patty topped with cheese, lettuce, tomato, and pickles, served on a toasted bun.",
                            Img = "beef_burger.jpg",
                            IsDeleted = false,
                            Name = "Beef Burger"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Assorted fresh vegetables stir-fried to perfection in a flavorful sauce, served over steamed rice.",
                            Img = "vegetable_stir_fry.jpg",
                            IsDeleted = false,
                            Name = "Vegetable Stir-Fry"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Homemade ravioli stuffed with succulent lobster meat, served with a creamy tomato sauce.",
                            Img = "lobster_ravioli.jpg",
                            IsDeleted = false,
                            Name = "Lobster Ravioli"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Tender pork tenderloin marinated in a savory blend of herbs and spices, grilled to perfection.",
                            Img = "pork_tenderloin.jpg",
                            IsDeleted = false,
                            Name = "Pork Tenderloin"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Slices of breaded and fried eggplant layered with marinara sauce and melted mozzarella cheese.",
                            Img = "eggplant_parmesan.jpg",
                            IsDeleted = false,
                            Name = "Eggplant Parmesan"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Plump shrimp sautéed in garlic butter and white wine, served over a bed of linguine pasta.",
                            Img = "shrimp_scampi.jpg",
                            IsDeleted = false,
                            Name = "Shrimp Scampi"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Creamy risotto cooked with fresh mushrooms, Parmesan cheese, and a hint of truffle oil.",
                            Img = "mushroom_risotto.jpg",
                            IsDeleted = false,
                            Name = "Mushroom Risotto"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Grilled steak served with a side of crispy French fries and a tangy dipping sauce.",
                            Img = "steak_frites.jpg",
                            IsDeleted = false,
                            Name = "Steak Frites"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Classic New York-style cheesecake with a buttery graham cracker crust and creamy filling.",
                            Img = "cheesecake.jpg",
                            IsDeleted = false,
                            Name = "Cheesecake"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Layers of espresso-soaked ladyfingers and creamy mascarpone cheese, dusted with cocoa powder.",
                            Img = "tiramisu.jpg",
                            IsDeleted = false,
                            Name = "Tiramisu"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Homemade apple pie with a flaky crust and a sweet and tangy apple filling.",
                            Img = "apple_pie.jpg",
                            IsDeleted = false,
                            Name = "Apple Pie"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Velvety smooth chocolate mousse topped with a dollop of whipped cream and chocolate shavings.",
                            Img = "chocolate_mousse.jpg",
                            IsDeleted = false,
                            Name = "Chocolate Mousse"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Light and fluffy shortcake layered with fresh strawberries and whipped cream.",
                            Img = "strawberry_shortcake.jpg",
                            IsDeleted = false,
                            Name = "Strawberry Shortcake"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Tangy lemon filling in a buttery tart shell, topped with a dusting of powdered sugar.",
                            Img = "lemon_tart.jpg",
                            IsDeleted = false,
                            Name = "Lemon Tart"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Smooth and creamy Italian dessert made with sweetened cream and gelatin.",
                            Img = "panna_cotta.jpg",
                            IsDeleted = false,
                            Name = "Panna Cotta"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "Moist and velvety red velvet cake with layers of cream cheese frosting.",
                            Img = "red_velvet_cake.jpg",
                            IsDeleted = false,
                            Name = "Red Velvet Cake"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Refreshing pie made with tangy key lime juice and a sweet graham cracker crust.",
                            Img = "key_lime_pie.jpg",
                            IsDeleted = false,
                            Name = "Key Lime Pie"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "Classic homemade chocolate chip cookies with gooey chocolate chips and a soft, chewy texture.",
                            Img = "chocolate_chip_cookies.jpg",
                            IsDeleted = false,
                            Name = "Chocolate Chip Cookies"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Description = "Chilled coffee served over ice with a splash of milk and a hint of sweetness.",
                            Img = "iced_coffee.jpg",
                            IsDeleted = false,
                            Name = "Iced Coffee"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Description = "Refreshing smoothie made with ripe mangoes, yogurt, and a touch of honey.",
                            Img = "mango_smoothie.jpg",
                            IsDeleted = false,
                            Name = "Mango Smoothie"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Description = "Steeped green tea leaves with a delicate and soothing flavor.",
                            Img = "green_tea.jpg",
                            IsDeleted = false,
                            Name = "Green Tea"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Description = "Freshly squeezed orange juice packed with vitamin C and a burst of citrus flavor.",
                            Img = "orange_juice.jpg",
                            IsDeleted = false,
                            Name = "Orange Juice"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Description = "Homemade lemonade made with freshly squeezed lemons and a touch of sweetness.",
                            Img = "lemonade.jpg",
                            IsDeleted = false,
                            Name = "Lemonade"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Description = "Classic Cuban cocktail made with rum, fresh mint leaves, lime juice, and a hint of sweetness.",
                            Img = "mojito.jpg",
                            IsDeleted = false,
                            Name = "Mojito"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Description = "Rich and creamy hot chocolate topped with whipped cream and chocolate shavings.",
                            Img = "hot_chocolate.jpg",
                            IsDeleted = false,
                            Name = "Hot Chocolate"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Description = "Bubbly and refreshing carbonated water with a clean and crisp taste.",
                            Img = "sparkling_water.jpg",
                            IsDeleted = false,
                            Name = "Sparkling Water"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Description = "Chilled black tea served over ice, optionally sweetened and garnished with a slice of lemon.",
                            Img = "iced_tea.jpg",
                            IsDeleted = false,
                            Name = "Iced Tea"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Description = "A tropical blend of assorted fruit juices with a sweet and tangy flavor.",
                            Img = "fruit_punch.jpg",
                            IsDeleted = false,
                            Name = "Fruit Punch"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            Description = "Classic Caesar salad with crisp romaine lettuce, Parmesan cheese, croutons, and tangy Caesar dressing.",
                            Img = "caesar_salad.jpg",
                            IsDeleted = false,
                            Name = "Caesar Salad"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            Description = "Fresh mozzarella cheese, ripe tomatoes, and basil leaves drizzled with balsamic glaze and olive oil.",
                            Img = "caprese_salad.jpg",
                            IsDeleted = false,
                            Name = "Caprese Salad"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            Description = "Classic Greek salad with fresh lettuce, tomatoes, cucumbers, olives, feta cheese, and a tangy dressing.",
                            Img = "greek_salad.jpg",
                            IsDeleted = false,
                            Name = "Greek Salad"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            Description = "Assorted greens topped with grilled chicken, avocado, bacon, hard-boiled eggs, and blue cheese crumbles.",
                            Img = "cobb_salad.jpg",
                            IsDeleted = false,
                            Name = "Cobb Salad"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            Description = "Fresh spinach leaves topped with sliced strawberries, goat cheese, and a light vinaigrette dressing.",
                            Img = "spinach_salad.jpg",
                            IsDeleted = false,
                            Name = "Spinach Salad"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            Description = "A French salad made with tuna, boiled eggs, green beans, potatoes, olives, and a Dijon vinaigrette.",
                            Img = "nicoise_salad.jpg",
                            IsDeleted = false,
                            Name = "Nicoise Salad"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            Description = "A refreshing salad made with crisp apples, celery, grapes, walnuts, and a creamy dressing.",
                            Img = "waldorf_salad.jpg",
                            IsDeleted = false,
                            Name = "Waldorf Salad"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Description = "A vibrant salad with mixed greens, grilled corn, black beans, tomatoes, avocado, and a zesty dressing.",
                            Img = "mexican_salad.jpg",
                            IsDeleted = false,
                            Name = "Mexican Salad"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            Description = "A protein-packed salad made with flaky tuna, crunchy vegetables, and a tangy mayonnaise dressing.",
                            Img = "tuna_salad.jpg",
                            IsDeleted = false,
                            Name = "Tuna Salad"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Description = "A nutritious salad made with quinoa, fresh vegetables, herbs, and a zesty lemon dressing.",
                            Img = "quinoa_salad.jpg",
                            IsDeleted = false,
                            Name = "Quinoa Salad"
                        });
                });

            modelBuilder.Entity("RestoFlow.Infrastructure.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RestoFlow.Infrastructure.Data.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Seats = 4,
                            TableNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            Seats = 6,
                            TableNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Seats = 2,
                            TableNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            Seats = 8,
                            TableNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            Seats = 4,
                            TableNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            Seats = 6,
                            TableNumber = 6
                        },
                        new
                        {
                            Id = 7,
                            Seats = 2,
                            TableNumber = 7
                        },
                        new
                        {
                            Id = 8,
                            Seats = 4,
                            TableNumber = 8
                        },
                        new
                        {
                            Id = 9,
                            Seats = 6,
                            TableNumber = 9
                        },
                        new
                        {
                            Id = 10,
                            Seats = 2,
                            TableNumber = 10
                        },
                        new
                        {
                            Id = 11,
                            Seats = 4,
                            TableNumber = 11
                        },
                        new
                        {
                            Id = 12,
                            Seats = 6,
                            TableNumber = 12
                        },
                        new
                        {
                            Id = 13,
                            Seats = 2,
                            TableNumber = 13
                        },
                        new
                        {
                            Id = 14,
                            Seats = 4,
                            TableNumber = 14
                        },
                        new
                        {
                            Id = 15,
                            Seats = 6,
                            TableNumber = 15
                        },
                        new
                        {
                            Id = 16,
                            Seats = 2,
                            TableNumber = 16
                        },
                        new
                        {
                            Id = 17,
                            Seats = 4,
                            TableNumber = 17
                        },
                        new
                        {
                            Id = 18,
                            Seats = 6,
                            TableNumber = 18
                        },
                        new
                        {
                            Id = 19,
                            Seats = 2,
                            TableNumber = 19
                        },
                        new
                        {
                            Id = 20,
                            Seats = 4,
                            TableNumber = 20
                        },
                        new
                        {
                            Id = 21,
                            Seats = 6,
                            TableNumber = 21
                        },
                        new
                        {
                            Id = 22,
                            Seats = 2,
                            TableNumber = 22
                        },
                        new
                        {
                            Id = 23,
                            Seats = 4,
                            TableNumber = 23
                        },
                        new
                        {
                            Id = 24,
                            Seats = 6,
                            TableNumber = 24
                        },
                        new
                        {
                            Id = 25,
                            Seats = 2,
                            TableNumber = 25
                        },
                        new
                        {
                            Id = 26,
                            Seats = 4,
                            TableNumber = 26
                        },
                        new
                        {
                            Id = 27,
                            Seats = 6,
                            TableNumber = 27
                        },
                        new
                        {
                            Id = 28,
                            Seats = 2,
                            TableNumber = 28
                        },
                        new
                        {
                            Id = 29,
                            Seats = 4,
                            TableNumber = 29
                        },
                        new
                        {
                            Id = 30,
                            Seats = 6,
                            TableNumber = 30
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RestoFlow.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RestoFlow.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestoFlow.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RestoFlow.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestoFlow.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("RestoFlow.Infrastructure.Data.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RestoFlow.Infrastructure.Data.Models.OccupiedTable", b =>
                {
                    b.HasOne("RestoFlow.Infrastructure.Data.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestoFlow.Infrastructure.Data.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestoFlow.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestoFlow.Infrastructure.Data.Models.Order", b =>
                {
                    b.HasOne("RestoFlow.Infrastructure.Data.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestoFlow.Infrastructure.Data.Models.ApplicationUser", "EditedBy")
                        .WithMany()
                        .HasForeignKey("EditedById");

                    b.HasOne("RestoFlow.Infrastructure.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("EditedBy");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RestoFlow.Infrastructure.Data.Models.Product", b =>
                {
                    b.HasOne("RestoFlow.Infrastructure.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestoFlow.Infrastructure.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
